apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: shivathebravo/reactproductapp:29
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /app/build/config.js  # Mount path for the config file
              subPath: config.js
      volumes:
        - name: config
          configMap:
            name: react-config